# Generated by Django 4.2.7 on 2023-12-05 15:26

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=18, null=True, unique=True, validators=[users.models.phone_validator], verbose_name='phone number'),
        ),
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.ImageField(blank=True, upload_to=users.models.profile_photo, verbose_name='photo'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('USER', 'Пользователь'), ('ADMIN', 'Администратор')], default='USER', max_length=16, verbose_name='role'),
        ),
    ]
